spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydata?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

my:
  userName: 鲁秦顺